print("Welcome to Your Very Own Mad Lib, otherwise known as YVOML! Please answer each prompt.")
print()
Plural_noun_1 = input("Enter a plural noun. ")
Plural_noun_2 = input("Enter another plural noun. ")
Number_1 = int(input("Enter a number. "))
Ing_verb_1 = input("Enter a verb ending in ing. ")
print("Great! YVOML is now complete, here is the result:")
print("Welcome to the Cult of %s, we believe that %s are really gods in disguise!" %s (Plural_noun_1, Plural_noun_2))
print("We hold services %d days a week, and each service we hold a holy %s. %d Number_1 %s Ing_verb_1")
